#version: '3.8'

services:
  flask-app:
    build: ./app
    container_name: app  # 👈 important pour que NGINX reconnaisse "app" comme nom d'hôte
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    command: flask run  # 👈 évite l'erreur "= main"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
